version: "3.8"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./localFolder:/data/db
  account_service:
    build: ./
    volumes:
      - ./acount_service
    ports:
      - "8080:8080"
    depends_on:
      - mongo
networks:
  my_network:
    driver: bridge